version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    working_directory: ~/Newbie
    steps:
      - checkout
      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/Newbie

  test:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          - RAILS_ENV: test
      - image: mysql:5.7
        environment:
          - MYSQL_USER: root
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'
    working_directory: ~/Newbie
    steps:
      - checkout
      - run:
          name: Bundler を指定
          command: bundle -v
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run:
          name: バンドルインストール
          command: bundle check || bundle install
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: DBを待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: データベースをセットアップ
          command: bin/rails db:schema:load --trace
      - run:
          name: RSpec を並列実行
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
