default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  host: db

development:
  <<: *default
  database: webapp_development

test:
  <<: *default
  database: webapp_test
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: password
